version: '3'

services:
  service_lint_test:
    build:
        context: .
        dockerfile: Dockerfile.ci
    ports:
      - "8000:8000"
    env_file:
      - ./.env.ci
    networks:
        - custom
    depends_on:
        - db
  db:
    image: postgres:15
    env_file:
        -   ./.env.ci
    ports:
        - "5432:5432"
    networks:
        - custom

networks:
  custom:
    driver: bridge
