version: '3'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
        - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
        - "5432:5432"
    env_file:
        -   ./.env.dev
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7
    restart: always
    env_file:
        -   ./.env.dev
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
        - db

volumes:
    postgres_data:
    pgadmin_data: